### ISSUE TITLE
[TODO] Support SwiftPM, and any platform.

### ISSUE THREAD

**Issue by swain** [OneAfternoon/Ward#4]
We should support any platform target, as well as Swift Package Manager. This is a to do.

**Comment by lazyvar** [comment]
@smolster Swift PM is failing ```swift package update``` when using ```.package(url: "https://github.com/OneAfternoon/Ward.git", from: "1.0.0")```. The from version number is specifying the github release tag, which for 1.0.X, does not contain a manifest file ```Package.swift```. 

We have a couple options here. What are the outcomes of deleting all the current releases and redeclaring a 1.0? How would this affect our cocoapod?

**Comment by swain** [comment]
Done!

**Comment by swain** [comment]
@lazyvar I think the issue here is that we're using "v1.0.x" for our tags, as opposed to "1.0.x". We should do the second one.
